runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_ENV: local   # or production
  APP_DEBUG : true # or false 
  APP_LOG: errorlog
  APP_KEY: base64:sq5GjgnShwc7UYV9AKeDDd9ASTmSrBSR2agkB6533rA=
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_HOST: localhost
  DB_DATABASE:  laravel_db_test
  DB_USERNAME: laravel_db_test
  DB_PASSWORD: M4chup1chu21!
  DB_SOCKET: "/cloudsql/proud-armor-266716:us-central1:laraveltesting"

beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: "proud-armor-266716:us-central1:laraveltesting"